### ISSUE TITLE
Getting BulkWriteError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by cnouguier** [kalisio/k-openaq#7]
{ BulkWriteError: E11000 duplicate key error collection: odk.openaq index: time_1_properties.country_1_properties.location_1_properties.variable_1 dup key: { : new Date(1580320800000), : "CH", : "CH0002R", : "co" }
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at OrderedBulkOperation.handleWriteError (/opt/krawler/node_modules/mongodb/lib/bulk/common.js:1056:11)
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at resultHandler (/opt/krawler/node_modules/mongodb/lib/bulk/ordered.js:163:23)
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at handler (/opt/krawler/node_modules/mongodb-core/lib/topologies/replset.js:1197:22)
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at /opt/krawler/node_modules/mongodb-core/lib/connection/pool.js:532:18
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   index: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   code: 11000,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   errmsg: 'E11000 duplicate key error collection: odk.openaq index: time_1_properties.country_1_properties.location_1_properties.variable_1 dup key: { : new Date(1580320800000), : "CH", : "CH0002R", : "co" }',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   op:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |    { type: 'Feature',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      time: 2020-01-29T18:00:00.000Z,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      geometry: { type: 'Point', coordinates: [Array] },
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      properties:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |       { name: 'CH0002R [Vaud]',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         country: 'CH',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         location: 'CH0002R',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         variable: 'co',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         co: 169.1,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         unit: 'µg/m³',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         sourceName: 'EEA Switzerland',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         averagingPeriod: [Object] },
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      _id: 5e31e446d92e3e00079336d0 },
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   name: 'BulkWriteError',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   driver: true,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   err:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |    { index: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      code: 11000,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      errmsg: 'E11000 duplicate key error collection: odk.openaq index: time_1_properties.country_1_properties.location_1_properties.variable_1 dup key: { : new Date(1580320800000), : "CH", : "CH0002R", : "co" }',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      op:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |       { type: 'Feature',
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         time: 2020-01-29T18:00:00.000Z,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         geometry: [Object],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         properties: [Object],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         _id: 5e31e446d92e3e00079336d0 } },
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   result:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |    BulkWriteResult {
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |      result:
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |       { ok: 1,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         writeErrors: [Array],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         writeConcernErrors: [],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         insertedIds: [Array],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         nInserted: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         nUpserted: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         nMatched: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         nModified: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         nRemoved: 0,
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         upserted: [],
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |         lastOp: [Object] } },
kargo-air_openaq.1.x74dteui1ikm@test-worker-1    |   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by cnouguier** [comment]
Works for now
